import json
from fastapi import APIRouter, Depends, Request, HTTPException
from modules.payments.model import (
    get_user_tier,
    create_payment_record,
    update_user_tier_on_payment,
    TIER_ORDER,
)
from modules.payments.service import create_razorpay_order, verify_webhook_signature
from modules.payments.schemas import (
    CreateOrderRequest, 
    CreateOrderResponse, 
    WebhookResponse, 
    VerifyPaymentRequest, 
    VerifyPaymentResponse
)
from shared.dependencies import get_current_user
from shared.config import RAZORPAY_WEBHOOK_SECRET, RAZORPAY_KEY_SECRET

router = APIRouter(tags=["payments"])

VALID_TIERS = ["premium", "ultra"]


@router.post("/payments/create-order", response_model=CreateOrderResponse)
async def create_order(
    body: CreateOrderRequest,
    current_user: dict = Depends(get_current_user),
):
    """Create a Razorpay payment order for tier upgrade."""
    if body.target_tier not in VALID_TIERS:
        raise HTTPException(status_code=400, detail="Invalid tier. Choose 'premium' or 'ultra'.")

    current_tier = await get_user_tier(current_user["firebase_uid"])
    if current_tier is None:
        raise HTTPException(status_code=404, detail="User not found")

    current_idx = TIER_ORDER.index(current_tier)
    target_idx = TIER_ORDER.index(body.target_tier)

    if target_idx <= current_idx:
        if target_idx == current_idx:
            raise HTTPException(status_code=400, detail="Already on this tier")
        raise HTTPException(status_code=400, detail="Cannot downgrade tier")

    order = create_razorpay_order(body.target_tier)

    await create_payment_record(
        user_id=current_user["firebase_uid"],
        razorpay_order_id=order["order_id"],
        amount=order["amount"],
        currency=order["currency"],
        target_tier=body.target_tier,
    )

    return order


@router.post("/payments/webhook", response_model=WebhookResponse)
async def payment_webhook(request: Request):
    """Handle Razorpay payment webhook. Verifies HMAC-SHA256 signature."""
    body = await request.body()
    signature = request.headers.get("X-Razorpay-Signature", "")

    if not verify_webhook_signature(body, signature, RAZORPAY_WEBHOOK_SECRET):
        raise HTTPException(status_code=400, detail="Invalid webhook signature")

    try:
        payload = json.loads(body)
    except json.JSONDecodeError:
        raise HTTPException(status_code=400, detail="Invalid JSON payload")

    event = payload.get("event")
    if event in ["payment.captured", "order.paid"]:
        # Razorpay sends different payloads for different events.
        # For order.paid, the entity is often under payload.order.entity
        # For payment.captured, it's under payload.payment.entity
        payment_entity = payload.get("payload", {}).get("payment", {}).get("entity", {})
        order_entity = payload.get("payload", {}).get("order", {}).get("entity", {})
        
        order_id = payment_entity.get("order_id") or order_entity.get("id")
        payment_id = payment_entity.get("id") or "paid_via_order_event"
        
        if order_id and payment_id:
            await update_user_tier_on_payment(order_id, payment_id)

    return {"status": "ok"}


@router.post("/payments/verify", response_model=VerifyPaymentResponse)
async def verify_payment(
    body: VerifyPaymentRequest,
    current_user: dict = Depends(get_current_user),
):
    """Synchronously verify payment signature after frontend checkout."""
    # Verify the signature generated by Razorpay
    msg = f"{body.razorpay_order_id}|{body.razorpay_payment_id}".encode()
    if not verify_webhook_signature(msg, body.razorpay_signature, RAZORPAY_KEY_SECRET):
        raise HTTPException(status_code=400, detail="Invalid payment signature")

    # Proceed to legitimately process the upgrade synchronously
    await update_user_tier_on_payment(body.razorpay_order_id, body.razorpay_payment_id)

    return VerifyPaymentResponse(success=True, message="Tier upgraded successfully")
